### ISSUE TITLE
Failing Scenario

### ISSUE THREAD

**Issue by aleemb** [ryanseddon/react-frame-component#105]
The following `initialContent` fails for some reason,

```
<!DOCTYPE html><html><head>
  <link rel='stylesheet' href='http://example.org/'>
  <script>
  console.log('foo');
  </script>
</head>
<body><div>Foo</div></body></html>
```

But this works

```
<!DOCTYPE html><html><head>
  <script>
  console.log('foo');
  </script>
  <link rel='stylesheet' href='http://example.org/'>
</head>
<body><div>Foo</div></body></html>
```

**Comment by aleemb** [comment]
The error is `Uncaught TypeError: Cannot read property 'children' of null`

**Comment by edrpls** [comment]
I ran into the same issue, but in my case, it was because of a library being loaded: `<script src="foo.js"></script>` doesn't work.

But `<script defer src="foo.js"></script>` works. My guess is that since the first one blocks the page rendering, there is no body set by the time the component renders. Using defer doesn't block page rendering, therefore no error. Although I think the component should wait until the window has finished loading before rendering.

I'll see if I can make a PR for it.

**Comment by joetidee** [comment]
Any joy in getting this PR through?
