### ISSUE TITLE
Does not work with sandbox

### ISSUE THREAD

**Issue by ldub** [ryanseddon/react-frame-component#115]
If you add the attribute `sandbox="allow-scripts allow-same-origin"` then this works fine, however, if you add just `sandbox="allow-scripts"` then `this.getDoc()` returns null here:
https://github.com/ryanseddon/react-frame-component/blob/eac19e396940c23710ee99cdd20f1617da2f33e0/src/Frame.jsx#L58

And the page errors out . with `Cannot read property 'querySelector' of null`

**Comment by ryanseddon** [comment]
Because this runs in the parent context of the document I'm not sure you could ever get access to the document of the iframe as you'd have to break the sandbox.

You could maybe explore using postMessage to get around this but that's beyond the scope of this package. 

If you have any ideas on how this could be addressed I'm all ears.
