### ISSUE TITLE
Head prop does not properly support script tags

### ISSUE THREAD

**Issue by zbyte64** [ryanseddon/react-frame-component#15]
Scripts tags inside an iframe must be created with that iframe's document createElement method. It will render the tag but the browser will ignore loading the source code.

**Comment by ryanseddon** [comment]
PRs welcome

**Comment by zbyte64** [comment]
TBH I don't have a good solution, this is more to document the issue. React assumes the document that it is imported in. 

You can import React while binding to the iframe's window but that breaks if you use webpack: 
https://gist.github.com/zbyte64/070fa723b7fe278a602c

Or you can manually do the diffing yourself:
https://gist.github.com/zbyte64/89ea49eb11ed38e16003

So all my solutions have a large element of suck.

**Comment by ibash** [comment]
At the cost of only being able to set the script once you can use `iframe.open()/write()/close()` to inject the initial html into the page and that can include script tags and anything else.

Instead of this code here: `https://github.com/ryanseddon/react-frame-component/blob/master/index.js#L49`

Do something like:
```
if (!this._setInitialContent) {
  doc.clear()
  doc.open()
  doc.write(this.props.initialContent)
  doc.close()
  this._setInitialContent = true
}
```

Where `this.props.initialContent` is something like `'<!doctype html><html><body><div></div></body></html>'` and you can put script and whatever else into a head tag.

@ryanseddon if you want me to put together a PR with this change I'd be happy to.

ref: https://developer.zendesk.com/blog/rendering-to-iframes-in-react#rendercomponenttostring-and-iframe.openwriteclose
