### ISSUE TITLE
[Violation] Avoid using document.write()

### ISSUE THREAD

**Issue by davidb1** [ryanseddon/react-frame-component#169]
This is coming from:
```
    if (doc.body.children.length < 1) {
         doc.open('text/html', 'replace');
         doc.write(this.props.initialContent);
         doc.close();
    }
```

In Firefox this is an error and the frame won't load: `DOMException: "The operation is insecure."`

**Comment by ryanseddon** [comment]
What's the context for the error? Unfortunately document.write is the only viable solution right now. If I was to drop IE11 support `srcdoc` could be an alternative.

**Comment by davidb1** [comment]
> What's the context for the error? Unfortunately document.write is the only viable solution right now. If I was to drop IE11 support `srcdoc` could be an alternative.

It's been a while but as I remember - Firefox just refuses to load the component throwing a `DOMException` so it doesn't work there (in the context of an extension).

**Comment by ryanseddon** [comment]
@davidb1 I've cut an [alpha release](https://github.com/ryanseddon/react-frame-component/releases/tag/v5.0.0-alpha.0) that uses srcdoc can your try installing `react-frame-component@alpha` and see if that works.

**Comment by Pagebakers** [comment]
The alpha release is unchanged, i see no trace of srcdoc and doc.write is still used.

**Comment by ryanseddon** [comment]
@Pagebakers you sure you installed the alpha release? I can see it here https://npmfs.com/package/react-frame-component/5.0.0-alpha.0/lib/Frame.js#L137

**Comment by Pagebakers** [comment]
Ah thanks, i was looking in the commit on github.

Here's a potential fix for <= IE11

https://github.com/Pagebakers/react-frame-component/blob/master/src/Frame.jsx

**Comment by anthonyxiques** [comment]
Hey @ryanseddon 

Thanks for creating this component!

Would you be open to publishing the `srcdoc` version as a non-alpha version? Would like to contribute toward cost of your time to make that happen - let me know if that is a possibility 🙏 

We're seeing this warning now in Google PageSpeed Insights when this component is used:

![image](https://user-images.githubusercontent.com/3936097/114229983-8f8bdb00-9946-11eb-83c0-dfc8511188d3.png)

"Learn more" links to [https://web.dev/no-document-write](https://web.dev/no-document-write).

Microsoft has also stopped supporting IE11 already for Teams, and they are [discontinuing support of IE11](https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666) for Microsoft 365 on August 17.

Thank you for considering 🙂

**Comment by ryanseddon** [comment]
Hey @anthonyxiques 

No worries I think it has sat enough for me to push out a new major release, I assume you've tested your implementation with the alpha release and it all works as expected?

> Would like to contribute toward cost of your time to make that happen - let me know if that is a possibility 🙏
I've been meaning to setup the sponsor feature for a while now so maybe when that's done you can donate me a coffee!

**Comment by ryanseddon** [comment]
v5 is now the [latest release](https://github.com/ryanseddon/react-frame-component/releases/tag/v5.0.0)

**Comment by anthonyxiques** [comment]
Thank you so much @ryanseddon!

**Comment by andrewpye** [comment]
Hi @ryanseddon, thanks for the library! My colleagues and I have been trying to update to v5 to remove the `document.write()` demerit mentioned by @anthonyxiques [previously](https://github.com/ryanseddon/react-frame-component/issues/169#issuecomment-816917779). After updating, the `Frame` component works just fine, but we've found that the update causes the tokens generated by a v3 recaptcha in our frame's content to no longer be verifiable by the recaptcha service. Do you have any idea what could be causing this? Perhaps using `srcdoc` changes something about how recaptcha perceives the user? Thanks in advance!

**Comment by ryanseddon** [comment]
@andrewpye not sure whats going on without some more info, can you create a new issue with some reproducible code?

**Comment by andrewpye** [comment]
> @andrewpye not sure whats going on without some more info, can you create a new issue with some reproducible code?

@ryanseddon the difficulty with this is that we're using Recaptcha v3, so the flow is:

1. User submits a form from with a `Frame` instance;
2. We invoke Recaptcha and obtain a token;
3. We send that token to our back end (Rails) where we verify the token by sending it to Recaptcha.

When using v4 of `react-frame-component`, the token is generated and validates just fine in our back end. After updating our front end to v5 of `react-frame-component`, Recaptcha still generates a token in our front end, but it fails validation when we send it for verification to Recaptcha from our back end. Nothing else has changed 😬 So, a reproduction would require setting up a front end, back end, and Recaptcha keys, and I'm honestly not sure how to do that 😅 Do you have any suggestions?

In the meantime I'll try setting up a repo with front and back ends contained within it, and leave it up to whoever uses it for testing to provide their own Recaptcha keys 🤞

**Comment by andrewpye** [comment]
@ryanseddon while trying (and failing 😅) to build a reproduction of this, I noticed something that might be responsible. On `react-frame-component` v4, the `iframe` rendered by the `Frame` component inherits the parent window's `location`:

<img width="1055" alt="react-frame-component v4" src="https://github.com/ryanseddon/react-frame-component/assets/5737342/6d1853c1-d51c-42cc-a522-24eb0f63464c">

As can be seen in the above screenshot, Recaptcha loads successfully. However, after switching to `react-frame-component` v5, the `iframe`'s `location` is now `about:srcdoc` (because of course `srcdoc` is being used to populate the frame's content):

<img width="806" alt="react-frame-component v5" src="https://github.com/ryanseddon/react-frame-component/assets/5737342/d3139095-40f3-47d5-854e-6ccf3984cfba">

In this case, Recaptcha shows an error, because the frame's domain no longer matches any of the domains that the Recaptcha was configured to be used on. I haven't been able to verify whether this is the cause of us starting to see Recaptcha verification failing after updating `react-frame-component`, but it seems quite possible. I'm not sure I have access to our org's Recaptcha configurations/settings, but will see if I can find them from someone and check what domains the Recaptchas are configured to be used on 🤞

**Comment by ryanseddon** [comment]
Thanks for the through investigation! I think your only solution here is to pin to v4 so it uses document.write and has the same origin as the parent

**Comment by ryanseddon** [comment]
Have you tried recaptcha v3? Wondering if the error still persists in the latest version

**Comment by andrewpye** [comment]
>Have you tried recaptcha v3?

Yes, that's what we're using 😞

>I think your only solution here is to pin to v4 so it uses document.write and has the same origin as the parent

Unfortunately our use case is in an app that's listed on a third-party app store, and there are concerns that the `document.write()` calls present in v4 introduce a demerit in Lighthouse reporting which could result in us being penalised in their listings 😬 More generally, we'd also like to be able to keep our dependencies as up to date as possible.

I've been wondering about the possibility of adding an option to allow using `innerHTML` to populate the frame's initial contents instead of `srcDoc` – what are your thoughts? I've seen the [discussion](https://github.com/ryanseddon/react-frame-component/pull/80) around the limitations of this approach and my thinking would be that `srcDoc` would still be the default method, but that allowing `innerHTML` might allow some workarounds for people in similar situations to the one we're in with Recaptcha 🤔 If you think it's worthwhile and it doesn't go against the ethos of the package, I'd be happy to try putting a PR together for it.

**Comment by a-fournier** [comment]
I got exactly the same problem on my side with GoogleMaps API key. We got the following error : "RefererNotAllowedMapError, about:srcdoc". I work with typescript and functional component so, using the v4 is not really possible.

**Comment by ryanseddon** [comment]
@andrewpye I would be open to a PR to add an escape hatch for this usecase. I know from testing that innerHTML doesn't work in all browsers.

Your best approach would be to either add a prop like `dangerouslyUseDocWrite` or something along those lines and fallback to the old approach. Or look into using ` src="data:text/html,<p>Some HTML</p>"` on the iframe to do a similar srcdoc approach.

**Comment by andrewpye** [comment]
Following up on this, I've tested using `innerHTML` as a fallback and found that when using that method, the frame's location becomes `about:blank`, which also causes Recaptcha to fail to initialise in the same way as the `srcDoc` issue. The only workaround I've found so far is to use `innerHTML` and set the frame's `src` to either the current location or `localhost` – Recaptcha then loads successfully (because the Recaptcha I'm testing with is configured to allow all domains, which is our use case), but of course the frame begins loading whatever was specified in the `src` until the frame loads and the `innerHTML` gets set. So although this works in our use case, it feels very hacky and I'm interested to see if you have any suggestions for improvement. Thanks!

**Comment by ryanseddon** [comment]
I wonder if it might be worth exploring converting the frame contents to static markup and generating a blob url to set as the iframe src?

```jsx
import { renderToStaticMarkup } from "react-dom/server";

function Contents() {
  return (
    <>
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
    </>
  );
}

const markup = renderToStaticMarkup(<Contents />);
console.log(markup);

const blob = new Blob([markup], { type: "text/html" });
const objectURL = URL.createObjectURL(blob);

export default function App() {
  return (
    <div className="App">
      <Frame>
        <h1>Hello CodeSandbox</h1>
        <h2>Start editing to see some magic happen!</h2>
      </Frame>
      <iframe src={objectURL}></iframe>
    </div>
  );
}
```

The origin of a object url looks like this `blob:http://localhost:3000/66275ce8-e616-46c7-0867-16131f5747b1`. I'm not sure if recaptcha considers this same origin and I don't have a recaptcha account to try it out on but might be an avenue to explore?

**Comment by andrewpye** [comment]
Thanks for the suggestion @ryanseddon, I'd never have thought of trying a `blob` URL! A `blob` `src` allows the parent app access to the frame's window and document so it's more workable in the context of the `Frame` component than the `data` URL approach, but unfortunately it seems to suffer the same issue with Recaptcha not liking the protocol and again giving the `Invalid domain for site key` error on initialisation 😢

Much as I hate to step away from a challenge, I don't think I can justify any more time trying to make progress towards being able to avoid `document.write()` _and_ have Recaptcha work in the frame. With that in mind, I'll put together a PR based on your earlier suggestion to add a `dangerouslyUseDocWrite` prop as an "escape hatch" so that people using `Frame` with services like Recaptcha, Google Maps etc. inside can continue to update `react-frame-component` in their apps and not get stuck at v4.

Thanks again for your work on this and the great suggestions – much appreciated 😊
