### ISSUE TITLE
React data attributes conflicting with existing react components

### ISSUE THREAD

**Issue by nelix** [ryanseddon/react-frame-component#3]
I am using react-frame-component from a chrome extension content script, if I load it into a page that is already using react  I get this error: 
Uncaught Error: Invariant Violation: ReactMount: Two valid but unequal nodes with the same `data-reactid`: .0.0 
is there a way to work around this?

**Comment by nelix** [comment]
should we add comments about the id name spacing to the readme?

**Comment by KelWill** [comment]
nelix thanks for the hack -- worked perfectly!

@ryanseddon -- any chance we could add that line of code to react-frame-component? It seems like the default should be for it to have a different data-reactid than the normal one so that anything in an iframe doesn't conflict with a regular react project.

**Comment by ryanseddon** [comment]
I'm not sure that should be part of this library, it should definitely be added to the readme. Wanna do a PR?

**Comment by ryanseddon** [comment]
This is fixed via #22
