### ISSUE TITLE
Ordering of `componentDidUpdate` and DOM updates

### ISSUE THREAD

**Issue by ConradIrwin** [ryanseddon/react-frame-component#34]
Hey! Right now there's an interesting ordering difference in terms of life-cycle for the frame component as opposed to normal React components. In usual react code `componentDidUpdate` of a parent component is called after the updates of its child components have been flushed to the DOM, but with the use of `unstable_renderComponentIntoNode`, `componentDidUpdate` of the parent actually triggers *before* the DOM in the iframe is updated.

There are two possible solutions to this:
* Somehow override React's queueing of component updates so that this particular one happens immediately (probably quite hard, but would provide amazing user experience)
* Provide a callback that is passed into `unstable_renderSubtreeIntoContainer` so that user's can handle the life-cycle manually (probably quite easy)

**Comment by ryanseddon** [comment]
@ibash any thoughts on this? I'm not super familiar with `unstable_renderSubtreeIntoContainer`

**Comment by ibash** [comment]
Hey @ryanseddon me and @ConradIrwin actually work together :)

- `ReactDOM.unstable_renderSubtreeIntoContainer` is the exact same as `ReactDOM.render` except that it passes a parent component, which makes context work.
- Another possibility could be to override `updateComponent`, but that may be brittle as well
- The PR I put forward goes the callback route, since it's unlikely react would break that anytime soon

ref: https://github.com/facebook/react/blob/master/src/renderers/dom/client/ReactMount.js#L504
ref: https://github.com/facebook/react/blob/master/src/renderers/shared/reconciler/ReactCompositeComponent.js#L651

**Comment by ryanseddon** [comment]
Gonna close this now due to merging #35.
