### ISSUE TITLE
Full HTML document rendering

### ISSUE THREAD

**Issue by GetContented** [ryanseddon/react-frame-component#4]
Is there any way to render an entire document in an iFrame? My reasons are to provide full HTML document preview, but with React's brilliant ability to update everything.

I've tried several things. React seems to have an html element, but I couldn't really seem to get it to work very well. Is this something you've tried?

**Comment by JulianLeviston** [comment]
Anyone? @ryanseddon ?

**Comment by zbyte64** [comment]
So let's say you want to render an iframe in a controlled manner in the browser, we might be tempted to do:

  &lt;Frame&gt;
    &lt;html&gt;
      &lt;head&gt;
         &lt;link href="some link"/&gt;
         &lt;script type="text/javascript" src="some js"&gt;&lt;/script&gt;
      &lt;/head&gt;
      &lt;body&gt;Hello World&lt;/body&gt;
    &lt;/html&gt;
  &lt;/Frame&gt;

This sounds nice but is difficult to implement for the following reasons:
* head and body must be written to separately, you can't mount at an html/root node, only on body and head
* head tags should be created using the iframe's DOM so that javascript will be loaded

For my own project I ended up manually difing the head state, not fun.

**Comment by JulianLeviston** [comment]
Still no news on this front, it seems... there are a couple of open issues in react proper about it. I'm not sure if they encompass scripts, though...

**Comment by darbs** [comment]
something like [this](https://gist.github.com/darbs/f9882510670c73aa9458)?

**Comment by ryanseddon** [comment]
We just landed `initialContent

**Comment by GetContented** [comment]
No that wouln't solve the use case we had. We ended up building our own version of this. However, we've also since deprecated React and we'll be using a different rendering mechanism (and language) ongoing. Thanks for the care/interest. :)

**Comment by GetContented** [comment]
Happy to close this. Please feel free to reopen if anyone else has this issue, I guess.
