### ISSUE TITLE
css classes inside iFrame not working

### ISSUE THREAD

**Issue by sankhadeeproy007** [ryanseddon/react-frame-component#49]
Hi, thanks for this component. I think I'm missing something here. If I use inline styles inside the iFrame components, they're working fine. However css with className="class" are not. Can you tell me what exactly I'm missing here?

**Comment by ryanseddon** [comment]
Can you create a reduced test case of what you're trying to do please.

**Comment by acusti** [comment]
@sankhadeeproy007 The css isn’t get applied to your rendered HTML (with `className="class"`) because it is living inside an iframe, which sandboxes it from the styles in its parent document. You just need to pass your stylesheet (or CSS in a `<style>` element) into the iframe itself. Simplest way is to just pass it as:

```js
<Frame>
  <link href="styles.css" rel="stylesheet" />
  { /* or: */ }
  <style dangerouslySetInnerHTML={ { __html: 'body { background: RebeccaPurple }' } } />
  { /* ...the rest of your frame contents */ }
</Frame>
```

**Comment by sankhadeeproy007** [comment]
Thanks for the help.
